version: "3.7"
services:
    db:
        image: postgres
        restart: unless-stopped
        container_name: GUILDED_BIO_DB
        environment:
            POSTGRES_DB: guildedbio
            POSTGRES_USER: bio_user
            POSTGRES_PASSWORD: bio_pass
        volumes:
            - bio-postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file: .env
    site:
        build:
            context: .
            dockerfile: ./Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        restart: "no"
        environment:
            DATABASE_URL: "postgresql://bio_user:bio_pass@db:5432/guildedbio?schema=public"
            NEXT_TELEMETRY_DISABLED: 1
        ports:
            - 3000:3000
        env_file: .env

volumes:
    bio-postgres-data:
